routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', [\App\Http\Controllers\HomeController::class, 'welcome'])->name('welcome-route');

Route::resource('user', 'UserController');
Route::resource('author', 'AuthorController');
Route::resource('book', 'BookController');
Route::resource('category', 'CategoryController');
Route::resource('genre', 'GenreController');
Route::resource('tag', 'TagController');
Route::resource('propstype', 'PropsTypeController');
Route::resource('propstypevalues', 'PropsTypeValueController');
Route::resource('readercard', 'ReaderCardController');
Route::resource('publisher', 'PublisherController');
Route::resource('booktag', 'BookTagController');
Route::resource('bookgenre', 'BookGenreController');
Route::resource('authorbook', 'AuthorBookController');
Route::resource('cardbookstates', 'CardBookStateController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{

    protected $table = 'books';
    public $timestamps = true;
    protected $fillable = array('name', 'annotation', 'isbn', 'publisher_id', 'publish_year', 'citation', 'pages', 'chapters', 'category_id', 'picture');

    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    public function authors()
    {
        return $this->belongsToMany('App\Author');
    }

    public function genres()
    {
        return $this->belongsToMany('App\Genre');
    }

    public function tags()
    {
        return $this->belongsToMany('App\Tag');
    }

    public function values()
    {
        return $this->hasMany('App\PropsTypeValue');
    }

    public function publisher()
    {
        return $this->belongsTo('App\Publisher');
    }

    public function cards()
    {
        return $this->belongsToMany('App\ReaderCard');
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Book;
use Illuminate\Http\Request;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $books = Book::paginate(18);
        return view('library.book.index', ['books' => $books]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Book $book
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Book $book)
    {
        $authors = $book->authors;
        $genres = $book->genres;
        return view('library.book.show', ['book' => $book, 'authors' => $authors, 'theAuthors' => $authors->count() > 1 ? 'Authors' : 'Author', 'theGenres' => $genres->count() > 1 ? 'Genres' : 'Genre'])
            ->withPublisher($book->publisher)
            ->withCategory($book->category)
            ->withGenres($genres)
            ->withTags($book->tags);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Book $book
     * @return \Illuminate\Http\Response
     */
    public function edit(Book $book)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Book $book
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Book $book)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Book $book
     * @return \Illuminate\Http\Response
     */
    public function destroy(Book $book)
    {
        //
    }
}

resources/views/library/book/index.blade.php
@extends('layouts.app')
@section('content')

    <section class="section">
        <div class="container has-text-centered">
            <h2 class="title">Books</h2>
            <p class="subtitle">This mountains of books</p>
            <div class="columns is-multiline">
                @foreach($books as $book)
                    <div class="column is-2">
                        <a href="{{route('book.show', $book->id)}}">
                            <div class="level">
                                <div class="level-item">
                                    <figure class="image is-128x128">
                                        <img class="is-rounded"
                                             src="{{asset('img/bg_circle.svg?primary=00d1b2')}}"
                                             alt=""></figure>
                                </div>
                            </div>
                            <h5 class="title is-5">{{$book['name']}}</h5>
                            {{--                        <p class="subtitle is-6">CEO</p>--}}
                            <p>{{Str::limit($book['annotation'], 50)}}</p>
                        </a>
                    </div>
                @endforeach
            </div>
        </div>
        <div>{{$books->links()}}</div>
    </section>
@endsection

resources/views/library/book/show.blade.php
@extends('layouts.app')
@section('content')

    <section class="section">
        <div class="container">
            <h2 class="title">Book: {{$book->name}}</h2>
            <h4 class="tag is-link is-medium">ISBN: {{$book->isbn}}</h4>
            <div class="columns">
                <div class="column is-8">
                    <a href="#"><img src="https://bulma.dev/placeholder/pictures/bg_4-3.svg?primary=00d1b2" alt=""></a>
                    <div class="column">
                        <h3 class="title is-spaced is-4">{{$book->name}}</h3>
                        <h4 class="tag is-primary is-medium">Annotation:</h4>
                        <p class="subtitle">{{$book->annotation}}</p>
                        <h4 class="tag is-primary is-medium">Citation:</h4>
                        <p class="subtitle">{{$book->citation}}</p>
                    </div>
                </div>


                <div class="column is-4">
                    <h3 class="title is-spaced is-4">{{$theAuthors}}</h3>
                    <div class="columns is-mobile is-multiline">
                        <ol>
                            @foreach($authors as $author)
                                <div class="column is-4-mobile is-12-tablet">
                                    <li class="ml-5">
                                        <a href="{{route('author.show', $author->id)}}">
                                            <h4 class="title is-5 has-text-primary">{{$author->name}}</h4>
                                        </a>
                                    </li>
                                    <p>{{Str::limit($author->description, 50)}}</p>
                                </div>
                            @endforeach
                        </ol>
                    </div>

                    <h3 class="title is-spaced is-4">Publisher</h3>
                    <div class="columns is-mobile is-multiline">
                        <div class="column is-4-mobile is-12-tablet">
                            <a href="{{route('publisher.show', $publisher->id)}}"><h4
                                    class="title is-5 has-text-primary">{{$publisher->name}}</h4></a>
                            <p>{{Str::limit($publisher->description, 50)}}</p>
                        </div>
                    </div>

                    <h3 class="title is-spaced is-4">Published in <span
                            class="tag is-large">{{$book->publish_year}}</span></h3>
                    <h3 class="title is-spaced is-4">Chapters/pages <span class="tag is-medium">{{$book->chapters}} / {{$book->pages}}</span>
                    </h3>

                    <h3 class="title is-spaced is-4">Category</h3>
                    <div class="columns is-mobile is-multiline">
                        <div class="column is-4-mobile is-12-tablet">
                            <a href="{{route('category.show', $category->id)}}"><h4
                                    class="title is-5 has-text-primary">{{$category->name}}</h4></a>
                            <p>{{Str::limit($category->description, 50)}}</p>
                        </div>
                    </div>

                    <h3 class="title is-spaced is-4">{{$theGenres}}</h3>
                    <div class="tags" style="justify-content: space-between;">
                        @foreach($genres as $genre)
                            <a href="{{route('genre.show', $genre->id)}}">
                                <span class="tag is-primary is-medium">{{$genre->name}}</span>
                            </a>
{{--                            <p>{{Str::limit($genre->description, 20)}}</p>--}}
                        @endforeach
                    </div>

                    <h3 class="title is-spaced is-4">Tags</h3>
                    <div class="tags" style="justify-content: space-between;">
                        @foreach($tags as $tag)
                            <a href="{{route('tag.show', $tag->id)}}">
                                <span class="tag is-link is-light">{{$tag->name}}</span>
                            </a>
                        @endforeach
                    </div>
                </div>
                <div class="columns">
                </div>
            </div>
        </div>
    </section>
@endsection