routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', [\App\Http\Controllers\HomeController::class, 'welcome'])->name('welcome-route');

Route::resource('user', 'UserController');
Route::resource('author', 'AuthorController');
Route::resource('book', 'BookController');
Route::resource('category', 'CategoryController');
Route::resource('genre', 'GenreController');
Route::resource('tag', 'TagController');
Route::resource('propstype', 'PropsTypeController');
Route::resource('propstypevalues', 'PropsTypeValueController');
Route::resource('readercard', 'ReaderCardController');
Route::resource('publisher', 'PublisherController');
Route::resource('booktag', 'BookTagController');
Route::resource('bookgenre', 'BookGenreController');
Route::resource('authorbook', 'AuthorBookController');
Route::resource('cardbookstates', 'CardBookStateController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Author.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Author extends Model
{

    protected $table = 'authors';
    public $timestamps = true;
    protected $fillable = array('name', 'description', 'avatar');

    public function books()
    {
        return $this->belongsToMany('App\Book');
    }

    public function categoryByBook()
    {
        return \App\Category::whereIn('id', $this->books->pluck('category_id'))->orderBy('name')->get();
    }

    public function genreByBook()
    {
        return \App\Genre::whereIn(
            'id',
            \App\BookGenre::
            whereIn('book_id', $this->books->pluck('id'))
                ->get()
                ->pluck('genre_id')
        )
            ->orderBy('name')
            ->get();
    }

}

app/Http/Controllers/AuthorController.php
<?php

namespace App\Http\Controllers;

use App\Author;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Request;
use Illuminate\View\View;

class AuthorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Factory|View
     */
    public function index()
    {
        $authors = Author::with('books')->paginate(18);
        return view('library.author.index', ['authors' => $authors]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Author  $author
     * @return Factory|View
     */
    public function show(Author $author)
    {
        $books = $author->books;
        $bookCategories = $author->categoryByBook();
        $bookGenres = $author->genreByBook();
        return view('library.author.show', ['author' => $author, 'books' => $books, 'bookCategories' => $bookCategories, 'bookGenres' => $bookGenres]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Author  $author
     * @return \Illuminate\Http\Response
     */
    public function edit(Author $author)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Author  $author
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Author $author)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Author  $author
     * @return \Illuminate\Http\Response
     */
    public function destroy(Author $author)
    {
        //
    }
}

resources/views/library/author/index.blade.php
@extends('layouts.app')
@section('content')

    <section class="section">
        <div class="container has-text-centered">
            <h2 class="title">Authors</h2>
            <p class="subtitle">They are the guys that made this mountains of books exist</p>
            <div class="columns is-multiline">
                @foreach($authors as $author)
                    <div class="column is-2">
                        <a href="{{route('author.show', $author->id)}}">
                            <div class="level">
                                <div class="level-item">
                                    <figure class="image is-128x128">
                                        <img class="is-rounded"
                                             src="{{asset('img/bg_circle.svg?primary=00d1b2')}}"
                                             alt=""></figure>
                                </div>
                            </div>
                            <h5 class="title is-5">{{$author['name']}}</h5>
                            <h6>Books - {{$author->books->count()}}</h6>
                            <p>{{Str::limit($author['description'], 50)}}</p>
                        </a>
                    </div>
                @endforeach
            </div>
        </div>
        <div>{{$authors->links()}}</div>
    </section>
@endsection

resources/views/library/author/show.blade.php
@extends('layouts.app')
@section('content')

    <section class="section">
        <div class="container">
            <h2 class="title">Author: {{$author->name}}</h2>
            <div class="columns">
                <div class="column is-6">
                    <a href="#"><img src="https://bulma.dev/placeholder/pictures/bg_4-3.svg?primary=00d1b2" alt=""></a>
                    <div class="column">
                        <h3 class="title is-spaced is-4">{{$author->name}}</h3>
                        <p class="subtitle">{{$author->description}}</p>
                        <br>
                        <h3 class="title is-spaced is-4">Categories of his books ({{$bookCategories->count()}})</h3>
                        <div class="tags" style="justify-content: space-between;">
                            @foreach($bookCategories as $bookCategory)
                                <span class="tag is-primary is-medium">{{$bookCategory->name}}</span>
                            @endforeach
                        </div>
                        <br>
                        <h3 class="title is-spaced is-4">Genres of his books {{$bookGenres->count()}}</h3>
                        <div class="tags" style="height: 100%;">
                            @foreach($bookGenres as $bookGenre)
                                <span class="tag is-link is-small">{{$bookGenre->name}}</span>
                            @endforeach
                        </div>
                    </div>
                </div>


                <div class="column is-6">
                    <h3 class="title is-spaced is-4">Books him created ({{$books->count()}})</h3>
                    <div class="columns is-mobile is-multiline">
                        <ol>
                            @foreach($books as $book)
                                <div class="column is-4-mobile is-12-tablet">
                                    <li class="ml-5"><a href="{{route('book.show', $book->id)}}"><h4 class="title is-5 has-text-primary">{{$book->name}}</h4>
                                        </a></li>
                                    <p>{{$book->annotation}}</p>
                                </div>
                            @endforeach
                        </ol>
                    </div>
                </div>
            </div>
            <div class="columns">
            </div>
        </div>
    </section>
@endsection